### ISSUE TITLE
I got this error when compiling the latest elytraOS

### ISSUE THREAD

**Issue by Trickbot199** [elytraOS/packages_apps_Launcher3#1]
FAILED: out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/Launcher3QuickStepLib.jar
rm -rf "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/classes" "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/anno" "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars" "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/Launcher3QuickStepLib.jar" && mkdir -p "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/classes" "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/anno" "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars" && out/soong/host/linux-x86/bin/zipsync -d out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars -l out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars/list -f "*.java" out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/gen/android/R.srcjar && (if [ -s out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars/list ] || [ -s out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/Launcher3QuickStepLib.jar.rsp ] ; then out/soong/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk11/linux-x86/bin/javac -J-Xmx2048M -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -proc:none -g:source,lines -Xlint:-dep-ann --system=out/soong/.intermediates/libcore/mmodules/core_platform_api/stable-core-platform-api-stubs-system-modules/android_common/system -classpath out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:out/soong/.intermediates/packages/modules/StatsD/framework/framework-statsd.stubs.module_lib/android_common/turbine-combined/framework-statsd.stubs.module_lib.jar:out/soong/.intermediates/frameworks/base/packages/SystemUI/shared/SystemUI-statsd/android_common/turbine-combined/SystemUI-statsd.jar:out/soong/.intermediates/frameworks/base/packages/SystemUI/shared/SystemUISharedLib/android_common/turbine-combined/SystemUISharedLib.jar:out/soong/.intermediates/packages/apps/Launcher3/Launcher3CommonDepsLib/android_common/turbine-combined/Launcher3CommonDepsLib.jar:out/soong/.intermediates/packages/apps/Launcher3/QuickstepResLib/android_common/turbine-combined/QuickstepResLib.jar:out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/kotlin/Launcher3QuickStepLib.jar -source 1.9 -target 1.9 -d out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/classes -s out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/anno @out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/Launcher3QuickStepLib.jar.rsp @out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars/list ; fi ) && out/soong/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/Launcher3QuickStepLib.jar -C out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/classes -D out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/classes && rm -rf "out/soong/.intermediates/packages/apps/Launcher3/Launcher3QuickStepLib/android_common/javac/srcjars"
packages/apps/Launcher3/src/com/android/launcher3/widget/LauncherAppWidgetHostView.java:115: error: cannot find symbol
        if (!Utilities.isWorkspaceEditAllowed(mLauncher.getApplicationContext())) return true;
                      ^
  symbol:   method isWorkspaceEditAllowed(Context)
  location: class Utilities
1 error
[ 74% 6181/8257] //packages/providers/UserDictionaryProvider:UserDictionaryProvider signapk [common]
[ 74% 6182/8257] //packages/modules/Connectivity/Tethering:Tethering r8 [common apex30]
Warning: Library class com.android.internal.util.IndentingPrintWriter extends program class android.util.IndentingPrintWriter
[ 74% 6183/8257] //vendor/support:VendorSupport-preference javac [common]
ninja: build stopped: subcommand failed.
20:07:24 ninja failed with: exit status 1

**Comment by ok-ano0s** [comment]
This is caused by the latest commit. Trying reverting it and build

**Comment by Trickbot199** [comment]
thanks
